### ISSUE TITLE
full reviews

### ISSUE THREAD

**Issue by brainplague** [epctex/goodreads-scraper#4]
Hey! I only get small parts of the reviews. Is it possible to get the full reviews somehow? Thanks!

**Comment by tugkan** [comment]
Hey @brainplague !

If possible, can you please share your dataset and input with us so that we can reproduce the issue?

Best!

**Comment by brainplague** [comment]
Hey @tugkan,

thanks for the fast answer. This should link to the run: https://console.apify.com/view/runs/e4XFrco2kmInrfg3e

Thanks!

**Comment by tugkan** [comment]
Hey @brainplague 

Sorry for the very late reply. Unfortunately, we couldn't resolve the bug for a while but now everything should be okay. You can use the latest version of the actor.

Please let us know if you encounter any other problems and we'll resolve them immediately.
Best
